### ISSUE TITLE
Blank page in Settings on Odysseyra1n

### ISSUE THREAD

**Issue by ZydePunk77** [tomaszpoliszuk/VolumeController#1]
Settings> Volume Controler> “In Portrait mode” and “in Landscape mode” are blank. 

Uninstalling/reinstalling tweak along with PreferenceLoader did not work. 

iPhone 7 iOS 13.7 Odysseyra1n. 

Works fine on iPhone X iOS 13.7 Checkra1n.

**Comment by tomaszpoliszuk** [comment]
There is bug in forked preferenceloader you are using.

You'll need preferenceloader from BigBoss repo - http://apt.thebigboss.org/repofiles/cydia/debs2.0/preferenceloader_2.2.5.deb or use alternative preferenceloader made by ArtikusHG, open sourced, available on repo -> https://artikushg.github.io/
